spring:
  application:
    name: cima

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

    hibernate:
      ddl-auto: validate

  datasource:
    url: jdbc:postgresql://localhost:5432/cima
    username: cima_user
    password: cima_password
    driver-class-name: org.postgresql.Driver

logging:
  level:
    root: ERROR